[package]
name = "Tron"
version = "0.1.0"
authors = ["Joey Walker <walkerj1@wit.edu>"]




[dependencies]
piston = "0.1.4"
piston2d-graphics = "0.1.4"
pistoncore-glutin_window = "0.1.0"
piston2d-opengl_graphics = "0.1.0"